version: '3'
services:
  app:
    image: nattanan/app:1.0.0
    container_name: my-app
    build: 
      dockerfile: dockerfile
    ports:
      - 13377:1337
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    networks:
      - toiscool
  db:
    image: postgres:latest
    container_name: tct-32-db
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - toiscool
networks:
  toiscool: